
FROM python:3.9

RUN apt-get update && apt-get install -y ghostscript

COPY requirements.txt .

RUN pip install -r requirements.txt
RUN pip install -U sanic-cors

EXPOSE 8000

WORKDIR /sanic

COPY . .

CMD ["python", "app.py"]